{% set name = "nmma" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nmma-{{ version }}.tar.gz
  sha256: 248016f2fd721edc7d8535f5f98e6091507deb675818738f2b073e70578da8a3

build:
  entry_points:
    - nmma-generation=nmma.pbilby.generation:main_nmma
    - nmma-gw-generation=nmma.pbilby.generation:main_nmma_gw
    - nmma-analysis=nmma.pbilby.analysis:main_nmma
    - nmma-gw-analysis=nmma.pbilby.analysis:main_nmma_gw
    - lightcurve-analysis=nmma.em.analysis:main
    - lightcurve-analysis-lbol=nmma.em.analysis_lbol:main
    - lightcurve-analysis-condor=nmma.em.analysis_condor:main
    - lightcurve-injection-summary=nmma.em.injection_summary:main
    - lightcurve-injection-slurm-setup=nmma.em.create_injection_slurm:main
    - lightcurve-injection-condor-setup=nmma.em.create_injection_condor:main
    - lightcurve-manual=nmma.em.manual:main
    - lightcurve-marginalization=nmma.em.lightcurve_marginalization:main
    - combine-EOS=nmma.em.combine_EOS:main
    - create-lightcurve-slurm=nmma.em.create_lightcurves_slurm:main
    - create-lightcurve-condor=nmma.em.create_lightcurves_condor:main
    - create-svdmodel=nmma.em.create_svdmodel:main
    - svdmodel-benchmark=nmma.em.svdmodel_benchmark:main
    - svdmodel-download=nmma.utils.models:main
    - lightcurve-generation=nmma.em.create_lightcurves:main
    - lightcurve-detection=nmma.em.detect_lightcurves:main
    - nmma-create-injection=nmma.eos.create_injection:main
    - gwem-resampling=nmma.em.gwem_resampling:main
    - gwem-resampling-condor=nmma.em.gwem_resampling_condor:main
    - gwem-Hubble-estimate=nmma.em.gwem_Hubble_estimate:main
    - convert-skyportal-lcs=tools.convert_skyportal_lcs:main
    - resample-grid=tools.resample_grid:main

  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.9,<3.12
  run:
    - arviz
    - astropy >=4.3.1
    - bilby >=1.2.0
    - bilby_pipe >=1.1.0
    - colorcet
    - corner
    - dust_extinction
    - dynesty
    - future
    - gwpy
    - healpy
    - h5py
    - joblib
    - lal
    - lalsimulation
    - ligo.skymap
    - ligo-followup-advocate
    - matplotlib-base <3.8,>=2.0
    - mpi4py
    - nestcheck
    - notebook
    - numpy >=1.9
    - pandas >=1.3.4,<2.0
    - parallel-bilby
    - p-tqdm
    - pymultinest
    - python >=3.7
    - pyyaml
    - requests
    - scikit-learn >=1.0.2,<1.2
    - scipy >=1.7.1
    - seaborn
    - sncosmo
    - tensorflow
    - tornado
    - tqdm
    - ultranest

test:
  imports:
    - nmma
  commands:
    - pip check
    - lightcurve-analysis --help
    - lightcurve-injection-summary --help
    - lightcurve-injection-slurm-setup --help
    - lightcurve-injection-condor-setup --help
    - lightcurve-marginalization --help
    - combine-EOS --help
    - create-lightcurve-slurm --help
    - create-lightcurve-condor --help
    - create-svdmodel --help
    - lightcurve-generation --help
    - lightcurve-detection --help
    - nmma-create-injection --help
    - gwem-resampling --help
    - gwem-resampling-condor --help
    - gwem-Hubble-estimate --help
    - lightcurve-analysis-condor --help
  requires:
    - pip
    - mpi4py
    - nestcheck

about:
  home: https://github.com/nuclear-multimessenger-astronomy/nmma
  summary: A nuclear physics multi-messenger Bayesian inference library
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sahiljhawar
    - mcoughlin
